### ISSUE TITLE
Setting `GameSettings` to impossible states doesn't provide good user interface feedback

### ISSUE THREAD

**Issue by b0r1ngx** [arkivanov/Minesweeper#16]
If we set settings with width 20 and height 20, there is only **400 cells**.

Entering mines more than **400** is generating wrong playing field (IMHO):
In the screenshot we can see:
1. Field is 20x20 (trust me),
2. I set 450 mines,
3. clicked on some cell on field,
4. game isn't ended.

In my opinion then `GameState.gameStatus` must come to `GameStatus.WIN`, or otherwise, before we generate a field with wrong parameters, we must pop-up a dialogue window to user that says that it can't create a field like that.

So upper possible bound must be `width * height - 1`, then when user clicks anywhere, `GameState.gameStatus` became `GameStatus.WIN`.

<img width="487" alt="image" src="https://github.com/arkivanov/Minesweeper/assets/55315908/c2893eea-f727-49b5-b578-b238d6a91863">

**Comment by arkivanov** [comment]
Yeah, there are many edge cases not covered I guess. I think in this particular case, the mine counts should be limited when the settings applied.

**Comment by b0r1ngx** [comment]
And one more thing that I noticed (when create some tests):
if we create next `GameComponent`, right with width = 20, height = 20, maxMines = 400:
```Kotlin
private val gameComponent = DefaultGameComponent(
    componentContext = DefaultComponentContext(lifecycle = lifecycle),
    storeFactory = DefaultStoreFactory(),
    settings = GameSettings(width = 20, height = 20, maxMines = 400),
    mainCoroutineContext = StandardTestDispatcher(scheduler = coroutineScheduler)
)
```

And run tests at `DefaultGameComponentTest` in `commonTest` module - we get failed results.

**Comment by b0r1ngx** [comment]
> And run tests at `DefaultGameComponentTest` in `commonTest` module - we get failed results.

Ahh, nevermind, its all because state is coming to WIN state, right after game field is generted, because all field are in mines.

the test is help me to understand it, and also one game run with this setting:
Expected :STARTED
Actual :WIN

**Comment by b0r1ngx** [comment]
> Yeah, there are many edge cases not covered I guess. I think in this particular case, the mine counts should be limited when the settings applied.

Yea its a good solution, i like that.

Я создал эту проблему, чтобы быть правопреемником реализации этой функции :)

**Comment by b0r1ngx** [comment]
> Yeah, there are many edge cases not covered I guess. I think in this particular case, the mine counts should be limited when the settings applied.

Yea its a good solution, I like that.

I'm created this issue to be assignee for this feature implementation :)

**Comment by arkivanov** [comment]
Assigned, thanks!
