### ISSUE TITLE
Migrate resources to Res.drawable

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Minesweeper#18]
We should update Kotlin to 1.9.23, Compose to 1.6.1, and migrate resources from name based `DrawableResource("icon_name")` to statically generated `Res.drawable.icon_name`. See the [resources docs](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html).

**Comment by arkivanov** [comment]
@b0r1ngx let me know if you would like to work on this.

**Comment by b0r1ngx** [comment]
Sure, lets me take a look on it and resolve!

**Comment by b0r1ngx** [comment]
What we must do with code, that using loops, to generate names?
```Kotlin
        cellOpenNumbers = buildMap {
            for (i in 1..8) {
                put(i, painterResource(DrawableResource("cell_open_$i.png")))
            }
        }
```

**Comment by b0r1ngx** [comment]
> What we must do with code, that using loops, to generate names?

I think how it accessed right now - is ok :?

**Comment by arkivanov** [comment]
I think we can write: 

```kotlin
cellOpenNumbers = mapOf(
    1 to painterResource(Res.drawable.cell_open_1),
    2 to painterResource(Res.drawable.cell_open_2),
    ...
)
```

This would also make it compile-time safe. What do you think?

**Comment by b0r1ngx** [comment]
Yes, this is looks like a work solution, but it was nice, if later, we can also use some loops to get resources with loops. (I googled a little bit and get nothing, didn't solve this task when works with Android previously)

I would use your example, thanks!

**Comment by b0r1ngx** [comment]
And awesome that u use this expression "compile-time safe", I would like to ask about what migrating resources giving us, can give a little explanation? Because at Jetbrains documentation nothing is said about what the performance it gives to us instead of DrawableResource.

**Comment by b0r1ngx** [comment]
Ahh.. I think u mean "compile-time safe" about that we start using mapOf, instead of buildMap - is I'm right?

**Comment by arkivanov** [comment]
By compile-time safe I mean that there will be compile error if we rename an icon file, and we'll need to fix the code. When we use `DrawableResource("<icon_file_name>")` then the project will compile just fine if we rename the file, but it will crash at runtime. So using statically generated names is safer.

**Comment by b0r1ngx** [comment]
I'm used wildcards for all names of resources (minesweeper.composeapp.generated.resources.*) - is it ok?

**Comment by b0r1ngx** [comment]
Let's I'm make a PR.

**Comment by arkivanov** [comment]
> I'm used wildcards for all names of resources

To be honest, I'm trying to avoid wildcards for all imports. There should be a static check for this, but I haven't setup Detekt yet.
